spring.application.name=Smartbank

spring.mvc.view.prefix=/views/
spring.mvc.view.suffix=.jsp


spring.datasource.driver-class-name= com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/bankDb
spring.datasource.username=root
spring.datasource.password=root



spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

server.port=9090

spring.http.encoding.charset=UTF-8
spring.http.encoding.enabled=true
spring.http.encoding.force=true